#!/usr/bin/env python3
"""Capture only the installed dependency closure of a local-llm-deploy extra."""
from __future__ import annotations

import argparse
from importlib import metadata
import platform


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--extra", required=True, choices=("download", "embedding", "rerank", "whisper", "dev"))
    args = parser.parse_args()
    try:
        from packaging.markers import default_environment
        from packaging.requirements import Requirement
        from packaging.utils import canonicalize_name
    except ImportError:
        parser.error("此维护命令需要 packaging；请在要记录的依赖环境显式安装它")
    environment = default_environment()
    selected, visited = {}, set()

    def visit(name, extras=()):
        name = canonicalize_name(name)
        contexts = frozenset(extras or ("",))
        marker_key = (name, contexts)
        if marker_key in visited:
            return
        visited.add(marker_key)
        dist = metadata.distribution(name)
        if name != "local-llm-deploy":
            selected[name] = dist.version
        for declaration in dist.requires or ():
            requirement = Requirement(declaration)
            if requirement.marker and not any(requirement.marker.evaluate(dict(environment, extra=extra)) for extra in contexts):
                continue
            installed = metadata.version(requirement.name)
            if requirement.specifier and installed not in requirement.specifier:
                parser.error(f"{name} requires {requirement}; installed {installed}. Run pip check first.")
            visit(requirement.name, requirement.extras)

    try:
        visit("local-llm-deploy", (args.extra,))
    except (metadata.PackageNotFoundError, ValueError) as exc:
        parser.error(str(exc))
    print(f"# Dependency closure: {platform.system()}-{platform.machine()} / Python {platform.python_version()}")
    print(f"# Generated by scripts/snapshot-dependencies.py --extra {args.extra}; validate in a fresh environment.")
    for name, version in sorted(selected.items()):
        print(f"{name}=={version}")


if __name__ == "__main__":
    main()
